const C=window.PLANT_STORIES_CONFIG||{},ok=C.supabaseUrl&&!C.supabaseUrl.includes("YOUR_"),sb=ok?supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null,D="plantStoriesDraftV3";
const demo=[{id:"d1",english_name:"Dandelion",german_name:"Löwenzahn",scientific_name:"Taraxacum officinale",place:"Beside a basketball court in Zürich",latitude:47.3769,longitude:8.5417,image_url:"",noticed_on:"2026-08-18",story:"I used to walk past this plant without noticing it. Then I saw one growing through a crack in the concrete beside the court. It looked fragile, but it had found exactly enough space to live. Its deep taproot helps it reach water, and its seeds travel with the wind.",meaning:"This plant teaches me that life does not always wait for the perfect place. Sometimes it begins with the smallest opening.",author:"Model entry",status:"approved"},{id:"d2",english_name:"Common ivy",german_name:"Efeu",scientific_name:"Hedera helix",place:"At Schulhaus Lachenzelg, Höngg",latitude:47.4084,longitude:8.4878,image_url:"",noticed_on:"2026-08-18",story:"It was the day of our sports tournament. While everyone else hurried across the schoolyard, I was waiting for a friend near the wall. I remember feeling nervous because my race was about to begin. Meanwhile, I noticed the ivy climbing quietly across the wall. By the time my friend arrived, I had been watching it for several minutes. Afterwards, I wondered how something that seemed so still could keep growing every day without anyone noticing.",meaning:"The ivy teaches me that growth is often invisible while it is happening. We usually notice it only when we look back.",author:"Model entry",status:"approved"}];
let map,pm,marker,lat=null,lng=null,file=null,current=null,filter="pending";
noticedDate.value=new Date().toISOString().slice(0,10);
document.querySelectorAll(".nav-button").forEach(b=>b.onclick=()=>show(b.dataset.view));
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".hidden-on-home").forEach(e=>e.classList.toggle("hidden",id==="homeView"));if(id==="mapView")setTimeout(loadMap,80);if(id==="teacherView")session()}
async function loadMap(){if(!map){map=L.map("map").setView([47.39,8.52],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map)}map.eachLayer(x=>{if(x instanceof L.Marker)map.removeLayer(x)});let plants=demo;if(ok){let r=await sb.from("plant_entries").select("*").eq("status","approved").order("noticed_on",{ascending:false});if(!r.error&&r.data.length)plants=r.data}plants.forEach(p=>{let m=L.marker([p.latitude,p.longitude]).addTo(map).bindTooltip(p.english_name);m.onclick=()=>render(p)});map.invalidateSize()}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function date(s){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(s+"T12:00:00"))}
function render(p){storyPanel.innerHTML=`${p.image_url?`<img class="story-image" src="${esc(p.image_url)}">`:`<div class="story-image empty-state"><div class="botanical-mark">❧</div></div>`}<h3 class="story-title">${esc(p.english_name)}</h3><p class="story-subtitle">${esc(p.german_name||"")}${p.scientific_name?` · <em>${esc(p.scientific_name)}</em>`:""}</p><p class="story-place">📍 ${esc(p.place)}</p><p class="noticed">Noticed on ${date(p.noticed_on)} by ${esc(p.author)}</p><button class="reveal-button" data-x="s">Read the story</button><div id="s" class="reveal-content hidden"><p>${esc(p.story)}</p></div><button class="reveal-button" data-x="m">What does this plant teach us?</button><div id="m" class="reveal-content hidden"><p>${esc(p.meaning)}</p></div>`;document.querySelectorAll(".reveal-button").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.x).classList.toggle("hidden"))}
imageInput.onchange=e=>{file=e.target.files[0];if(file){imagePreview.src=URL.createObjectURL(file);imagePreviewWrap.classList.remove("hidden")}}
useLocation.onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>setLoc(p.coords.latitude,p.coords.longitude,"Current location selected."),()=>toast("We could not access your location.")):toast("Location is not available.");
chooseOnMap.onclick=()=>{pickerMap.classList.remove("hidden");if(!pm){pm=L.map("pickerMap").setView([47.39,8.52],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(pm);pm.on("click",e=>{setLoc(e.latlng.lat,e.latlng.lng,"Location chosen on the map.");marker?marker.setLatLng(e.latlng):marker=L.marker(e.latlng).addTo(pm)})}setTimeout(()=>pm.invalidateSize(),80)}
function setLoc(a,b,t){lat=a;lng=b;plantForm.latitude.value=a;plantForm.longitude.value=b;locationStatus.textContent=t}
saveDraft.onclick=()=>{let x=Object.fromEntries(new FormData(plantForm).entries());x.latitude=lat;x.longitude=lng;localStorage.setItem(D,JSON.stringify(x));draftStatus.textContent="Draft saved on this device."}
let saved=localStorage.getItem(D);if(saved){let x=JSON.parse(saved);Object.entries(x).forEach(([k,v])=>{if(plantForm.elements[k]&&k!=="image"&&v!=null)plantForm.elements[k].value=v});if(x.latitude!=null)setLoc(+x.latitude,+x.longitude,"Saved location restored.");draftStatus.textContent="A saved draft was restored."}
plantForm.onsubmit=async e=>{e.preventDefault();if(lat===null)return toast("Please choose a location.");if(!ok)return toast("Connect Supabase before using shared submissions.");let d=new FormData(plantForm),image_url="";try{if(file){let path=crypto.randomUUID()+"."+file.name.split(".").pop(),u=await sb.storage.from("plant-images").upload(path,file);if(u.error)throw u.error;image_url=sb.storage.from("plant-images").getPublicUrl(path).data.publicUrl}let r=await sb.from("plant_entries").insert({english_name:d.get("english_name"),german_name:d.get("german_name"),scientific_name:d.get("scientific_name"),place:d.get("place"),latitude:lat,longitude:lng,image_url,noticed_on:d.get("noticed_on"),story:d.get("story"),meaning:d.get("meaning"),author:d.get("author"),status:"pending"});if(r.error)throw r.error;localStorage.removeItem(D);plantForm.reset();noticedDate.value=new Date().toISOString().slice(0,10);toast("Submitted for approval.")}catch(e){toast(e.message)}}
loginButton.onclick=async()=>{if(!ok)return loginMessage.textContent="Add Supabase settings in config.js first.";let r=await sb.auth.signInWithPassword({email:teacherEmail.value,password:teacherPassword.value});loginMessage.textContent=r.error?r.error.message:"";if(!r.error)dash()}
logoutButton.onclick=async()=>{await sb.auth.signOut();login()}
async function session(){if(!ok)return login();let r=await sb.auth.getSession();r.data.session?dash():login()}
function login(){teacherLogin.classList.remove("hidden");teacherDashboard.classList.add("hidden")}function dash(){teacherLogin.classList.add("hidden");teacherDashboard.classList.remove("hidden");loadSubs()}
document.querySelectorAll(".filter-button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter-button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.status;loadSubs()})
async function loadSubs(){let r=await sb.from("plant_entries").select("*").eq("status",filter).order("created_at",{ascending:false});if(r.error)return submissionList.innerHTML=`<p>${esc(r.error.message)}</p>`;submissionList.innerHTML=(r.data||[]).map(p=>`<article class="submission-item"><div><h3>${esc(p.english_name)} — ${esc(p.author)}</h3><p>${esc(p.place)} · Noticed ${date(p.noticed_on)}</p></div><button class="outline-button review" data-id="${p.id}">Review</button></article>`).join("")||"<p>No entries here.</p>";document.querySelectorAll(".review").forEach(b=>b.onclick=()=>open(r.data.find(x=>x.id===b.dataset.id)))}
function open(p){current=p;moderationPreview.innerHTML=`${p.image_url?`<img class="story-image" src="${esc(p.image_url)}">`:""}<h2>${esc(p.english_name)}</h2><p>📍 ${esc(p.place)}</p><p class="noticed">Noticed on ${date(p.noticed_on)} by ${esc(p.author)}</p><h3>Story</h3><p>${esc(p.story)}</p><h3>Meaning</h3><p>${esc(p.meaning)}</p>`;moderationDialog.showModal()}
approveSubmission.onclick=()=>status("approved");returnSubmission.onclick=()=>status("returned");deleteSubmission.onclick=async()=>{if(confirm("Delete this contribution?")){let r=await sb.from("plant_entries").delete().eq("id",current.id);if(r.error)return toast(r.error.message);moderationDialog.close();loadSubs()}}
editSubmission.onclick=async()=>{let s=prompt("Edit the story:",current.story);if(s===null)return;let m=prompt("Edit the meaning:",current.meaning);if(m===null)return;let r=await sb.from("plant_entries").update({story:s,meaning:m}).eq("id",current.id);if(r.error)return toast(r.error.message);current.story=s;current.meaning=m;open(current);toast("Changes saved.")}
async function status(s){let r=await sb.from("plant_entries").update({status:s}).eq("id",current.id);if(r.error)return toast(r.error.message);moderationDialog.close();loadSubs();toast(s==="approved"?"Published.":"Returned.")}
function toast(x){let t=document.getElementById("toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));