const samplePlants=[{id:1,englishName:"Dandelion",germanName:"Löwenzahn",scientificName:"Taraxacum officinale",place:"Beside a basketball court in Zürich",lat:47.3769,lng:8.5417,image:"",story:"I used to walk past this plant without noticing it. Then I saw one growing through a crack in the concrete beside the court. It looked fragile, but it had found exactly enough space to live. Its deep taproot helps it reach water, and its seeds travel with the wind.",meaning:"This plant teaches me that life does not always wait for the perfect place. Sometimes it begins with the smallest opening.",author:"Model entry"},{id:2,englishName:"Common ivy",germanName:"Efeu",scientificName:"Hedera helix",place:"On an old wall near the school",lat:47.3818,lng:8.5308,image:"",story:"At first I only saw the wall. When I looked again, the ivy seemed to be drawing its own map across the stone. It climbs with small aerial roots, stays green through winter and provides late food for insects.",meaning:"The ivy teaches me that slow change can still be powerful.",author:"Model entry"}];
const storedPlants=JSON.parse(localStorage.getItem("plantStoriesV2")||"[]");const plants=[...samplePlants,...storedPlants];const views=document.querySelectorAll(".view");const hiddenOnHome=document.querySelectorAll(".hidden-on-home");let map,pickerMap,pickerMarker;let selectedLat=null,selectedLng=null,currentImage="";
function showView(id){views.forEach(v=>v.classList.remove("active"));document.getElementById(id).classList.add("active");hiddenOnHome.forEach(el=>el.classList.toggle("hidden",id==="homeView"));if(id==="mapView")setTimeout(()=>{ensureMap();map.invalidateSize()},100)}document.querySelectorAll(".nav-button").forEach(btn=>btn.addEventListener("click",()=>showView(btn.dataset.view)));
function ensureMap(){if(map)return;map=L.map("map").setView([47.3769,8.5417],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);plants.forEach(plant=>{const marker=L.marker([plant.lat,plant.lng]).addTo(map);marker.bindTooltip(plant.englishName);marker.on("click",()=>renderPlant(plant))})}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}
function renderPlant(plant){const panel=document.getElementById("storyPanel");const image=plant.image?`<img class="story-image" src="${plant.image}" alt="${escapeHtml(plant.englishName)}">`:`<div class="story-image empty-state"><div class="botanical-mark">❧</div></div>`;panel.innerHTML=`${image}<h3 class="story-title">${escapeHtml(plant.englishName)}</h3><p class="story-subtitle">${escapeHtml(plant.germanName)}${plant.scientificName?` · <em>${escapeHtml(plant.scientificName)}</em>`:""}</p><p class="story-place">📍 ${escapeHtml(plant.place)}</p><section class="story-section"><h3>Story</h3><p>${escapeHtml(plant.story)}</p></section><section class="story-section"><h3>Meaning</h3><p>${escapeHtml(plant.meaning)}</p></section><p class="author">Contribution by ${escapeHtml(plant.author)}</p>`}
document.getElementById("imageInput").addEventListener("change",event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{currentImage=reader.result;const preview=document.getElementById("imagePreview");preview.innerHTML=`<img class="image-preview" src="${currentImage}" alt="Preview">`;preview.classList.remove("hidden")};reader.readAsDataURL(file)});
document.getElementById("useLocation").addEventListener("click",()=>{if(!navigator.geolocation){showToast("Location is not available in this browser.");return}document.getElementById("locationStatus").textContent="Finding your location…";navigator.geolocation.getCurrentPosition(pos=>setLocation(pos.coords.latitude,pos.coords.longitude,"Current location selected."),()=>showToast("We could not access your location."))});
document.getElementById("chooseOnMap").addEventListener("click",()=>{const picker=document.getElementById("pickerMap");picker.classList.remove("hidden");if(!pickerMap){pickerMap=L.map("pickerMap").setView([47.3769,8.5417],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(pickerMap);pickerMap.on("click",event=>{setLocation(event.latlng.lat,event.latlng.lng,"Location chosen on the map.");if(pickerMarker)pickerMarker.setLatLng(event.latlng);else pickerMarker=L.marker(event.latlng).addTo(pickerMap)})}setTimeout(()=>pickerMap.invalidateSize(),100)});
function setLocation(lat,lng,message){selectedLat=lat;selectedLng=lng;const form=document.getElementById("plantForm");form.lat.value=lat;form.lng.value=lng;document.getElementById("locationStatus").textContent=message}
document.getElementById("plantForm").addEventListener("submit",event=>{event.preventDefault();if(selectedLat===null||selectedLng===null){showToast("Please choose a location first.");return}const data=new FormData(event.currentTarget);const plant={id:Date.now(),englishName:data.get("englishName"),germanName:data.get("germanName"),scientificName:data.get("scientificName"),place:data.get("place"),lat:Number(data.get("lat")),lng:Number(data.get("lng")),image:currentImage,story:data.get("story"),meaning:data.get("meaning"),author:data.get("author")};const stored=JSON.parse(localStorage.getItem("plantStoriesV2")||"[]");stored.push(plant);localStorage.setItem("plantStoriesV2",JSON.stringify(stored));showToast("Saved in this browser. Opening preview…");setTimeout(()=>location.reload(),800)});
function showToast(message){const toast=document.getElementById("toast");toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)}
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
